# Generated by Django 3.0 on 2021-03-07 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('dairy', 'Dairy'), ('drinks', 'Drinks'), ('meats', 'Meats'), ('fruits and veggies', 'Fruit and Veggies'), ('condiments', 'Condiments'), ('snacks', 'Snacks'), ('pet food', 'Pet Food'), ('canned food', 'Canned Food'), ('dry goods', 'Dry Goods'), ('cleaning supplies', 'Cleaning Supplies')], default='dairy', max_length=50)),
                ('quantity', models.CharField(max_length=3)),
                ('description', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
